#ifndef __PINS__H__
#define __PINS__H__

#define PIN_NUM_MISO	GPIO_NUM_13
#define PIN_NUM_MOSI	GPIO_NUM_11
#define PIN_NUM_CLK		GPIO_NUM_12
#define PIN_NUM_CS		GPIO_NUM_10
#define PIN_NUM_MOTION	GPIO_NUM_9

#define PIN_NUM_I2C_SDA GPIO_NUM_7
#define PIN_NUM_I2C_SCL GPIO_NUM_8

#define PIN_BTN1		GPIO_NUM_1
#define PIN_BTN2		GPIO_NUM_2
#define PIN_BTN3		GPIO_NUM_3
#define PIN_BTN4		GPIO_NUM_4
#define PIN_BTN_SCROLL	GPIO_NUM_5
#define PIN_BTN_CFG		GPIO_NUM_6

#endif // __PINS__H__
